### PR TITLE
ASDPLNG-38 Initial SCM Review

### PR DESCRIPTION
**Pull request by bsper2**
Add CI
Ran PDK Update

Add support for new Class param profile_firewall::purge_all which can be used to tell Puppet it's ok to completely purge all unmanaged rules and unmanaged chains. This is set to true by default, and must be turned to false if you plan on using $ignores

Added more inbuilt_chains to complete the list of all the default chains. This gets rid of errors when purge_all is true where Puppet tries to delete builtin chains which is something it cannot do.

Updated default firewall rules so that it will:
Accept ALL ICMP from NCSA IPs
Accept only icmp echo from anywhere else
Added drop all for ip6tables

Updated README with extra details

### CODE REVIEW

**Comment by bsper2** [comment]
Added allow for Campus Nagios too

**Comment by billglick** [comment]
@bsper2 These changes look good to me. But you should probably do a git rebase to combine the 3 commits into a single commit.
@andylytical Did you want to specifically review this, or can I merge this PR?

**Comment by andylytical** [comment]
@billglick I do not have time to review today and don't want to hinder progress. I'm happy if you've reviewed it. Please have @bsper2 rebase before merge (best to keep intermediate commits out of history on main).

**Comment by bsper2** [comment]
@billglick Thanks for taking a look. @andylytical Wasn't sure how github would handle the squash and force push once the pull request had been made, but I guess I shouldn't be surprised that after trying it it worked just fine.

**Pull request merged**
